name: build-release

on:
  push:
    tags:
    - v*

jobs:
  build-release:
    name: Build Release Package
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.1.0-latest

    env:
      OMD_ROOT: /omd/sites/cmk
      OMD_SITE: cmk
      CMK_SITE_ID: cmk
      WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Initialize Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - uses: actions/checkout@v2
      - name: Setup links
        run: .devcontainer/symlink.sh
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH
      - name: Build Extension
        run: .devcontainer/build.sh
        id: cmkpkg

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.mkp'
